### ISSUE TITLE
Nexus release missing a container folder

### ISSUE THREAD

**Issue by probablynotpotato** [AlbertoRota/x4-Better-piracy#13]
Vortex doesn't install anything; looks like it would need a container folder in the zip for all mod content, otherwise it doesn't install right, and then complains (wrongly) that all (0) files are redundant.

**Comment by AlbertoRota** [comment]
Thank you very much for the report, should be fixed in the latest release.
Let me know how it goes since I don't use vortex :S

**Comment by probablynotpotato** [comment]
Thank you, looks all good now.
